CREATE DATABASE IF NOT EXISTS contact_book;
USE contact_book;

CREATE TABLE IF NOT EXISTS contacts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL UNIQUE,
  company VARCHAR(120) NULL,
  address VARCHAR(255) NULL,
  notes TEXT NULL,
  isLocked BOOLEAN NOT NULL DEFAULT FALSE,
  lockedBy VARCHAR(120) NULL,
  lockExpiresAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
